package com.sanmiao.wypread;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.sanmiao.wypread.bean.CheckBean;

/**
 * Entity mapped to table "WYPREAD".
 */
public class Wypread extends CheckBean{

    private Long id;
    private String name;
    private String bookPath;
    private String imgPath;
    private Integer readPosition;
    private String readJindu;
    private String quitePath;
    private String quiteChapter;
    private String quitePosition;
    private String writeName;
    private String classfiy;
    private String isDown;
    private String quiteJindu;
    private String fromFile;

    public Wypread() {
    }

    public Wypread(Long id) {
        this.id = id;
    }

    public Wypread(Long id, String name, String bookPath, String imgPath, Integer readPosition, String readJindu, String quitePath, String quiteChapter, String quitePosition, String writeName, String classfiy, String isDown, String quiteJindu, String fromFile) {
        this.id = id;
        this.name = name;
        this.bookPath = bookPath;
        this.imgPath = imgPath;
        this.readPosition = readPosition;
        this.readJindu = readJindu;
        this.quitePath = quitePath;
        this.quiteChapter = quiteChapter;
        this.quitePosition = quitePosition;
        this.writeName = writeName;
        this.classfiy = classfiy;
        this.isDown = isDown;
        this.quiteJindu = quiteJindu;
        this.fromFile = fromFile;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBookPath() {
        return bookPath;
    }

    public void setBookPath(String bookPath) {
        this.bookPath = bookPath;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public Integer getReadPosition() {
        return readPosition;
    }

    public void setReadPosition(Integer readPosition) {
        this.readPosition = readPosition;
    }

    public String getReadJindu() {
        return readJindu;
    }

    public void setReadJindu(String readJindu) {
        this.readJindu = readJindu;
    }

    public String getQuitePath() {
        return quitePath;
    }

    public void setQuitePath(String quitePath) {
        this.quitePath = quitePath;
    }

    public String getQuiteChapter() {
        return quiteChapter;
    }

    public void setQuiteChapter(String quiteChapter) {
        this.quiteChapter = quiteChapter;
    }

    public String getQuitePosition() {
        return quitePosition;
    }

    public void setQuitePosition(String quitePosition) {
        this.quitePosition = quitePosition;
    }

    public String getWriteName() {
        return writeName;
    }

    public void setWriteName(String writeName) {
        this.writeName = writeName;
    }

    public String getClassfiy() {
        return classfiy;
    }

    public void setClassfiy(String classfiy) {
        this.classfiy = classfiy;
    }

    public String getIsDown() {
        return isDown;
    }

    public void setIsDown(String isDown) {
        this.isDown = isDown;
    }

    public String getQuiteJindu() {
        return quiteJindu;
    }

    public void setQuiteJindu(String quiteJindu) {
        this.quiteJindu = quiteJindu;
    }

    public String getFromFile() {
        return fromFile;
    }

    public void setFromFile(String fromFile) {
        this.fromFile = fromFile;
    }

}
