package com.wypread.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sanmiao.wypread.Wypread;

import com.wypread.dao.WypreadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wypreadDaoConfig;

    private final WypreadDao wypreadDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wypreadDaoConfig = daoConfigMap.get(WypreadDao.class).clone();
        wypreadDaoConfig.initIdentityScope(type);

        wypreadDao = new WypreadDao(wypreadDaoConfig, this);

        registerDao(Wypread.class, wypreadDao);
    }
    
    public void clear() {
        wypreadDaoConfig.getIdentityScope().clear();
    }

    public WypreadDao getWypreadDao() {
        return wypreadDao;
    }

}
